FROM nginx:1.12

COPY default.conf /etc/nginx/conf.d/default.conf

#RUN mkdir -p  /etc/ssl/certs
#
#RUN mkdir -p  /etc/ssl/private
#
#
#RUN sed -i '/index.html index.htm;/ a\    server_tokens off;' /etc/nginx/nginx.conf


#COPY default.conf /etc/nginx/conf.d/default.conf
